services:
  - type: web
    name: livestock-manager
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn livestockManager.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: DEBUG
        value: False
      - key: RENDER
        value: True
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com livestock-manager.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: livestock_db
          property: connectionString

databases:
  - name: livestock_db
    ipAllowList: []
