# Generated by Django 5.0.4 on 2025-04-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', 'fix_animal_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='breed_obj',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='breed_ref',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='species_obj',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='species_ref',
        ),
    ]
