# Generated by Django 5.0.4 on 2025-04-13 22:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_userpreferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='new_owner',
        ),
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='previous_owner',
        ),
        migrations.RemoveField(
            model_name='ownershiptransfer',
            name='transfer_date',
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='livestock.owner'),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='livestock.owner'),
        ),
        migrations.AddField(
            model_name='ownershiptransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
