# Generated by Django 5.0.4 on 2025-04-13 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_notification'),
        ('livestock', 'new_health_record_model'),
    ]

    operations = [
    ]
