# Generated by Django 5.0.4 on 2025-04-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0007_alter_customuser_animal_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(
                error_messages={'unique': 'This email address is already registered.'},
                max_length=254,
                unique=True,
                verbose_name='Email Address'
            ),
        ),
    ]
