# Generated by Django 5.0.4 on 2025-04-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='breed',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('species', 'name')},
        ),
    ]
